# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Stiven-Gjekaj.AllTheTools
PackageVersion: 0.1.0
InstallerType: portable
Commands:
- att
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Stiven-Gjekaj/AllTheTools/releases/download/v0.1.0/att-0.1.0-x86_64-pc-windows-msvc.exe
  InstallerSha256: D39E4259C79744FE783721BC3377BDC7EEFA57420858A8EE0BF491903EDB9FB1
- Architecture: arm64
  InstallerUrl: https://github.com/Stiven-Gjekaj/AllTheTools/releases/download/v0.1.0/att-0.1.0-aarch64-pc-windows-msvc.exe
  InstallerSha256: B465CF46F2F963A2A8AC53CACBF4803FB717BEE8413F0ED7CBBFF08BB272F971
ManifestType: installer
ManifestVersion: 1.12.0
