# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Stiven-Gjekaj.HotDogStand
PackageVersion: 0.1.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: HotDogStand\HotDogStand.exe
  PortableCommandAlias: hotdogstand
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Stiven-Gjekaj/HotDogStand/releases/download/v0.1.1/HotDogStand-windows-x86_64.zip
  InstallerSha256: 690534F37533F5D9D139C733F69723AF21ECFDFE0FB5027857A21D208AA97306
ManifestType: installer
ManifestVersion: 1.12.0
